### ISSUE TITLE
Problema na redenrização

### ISSUE THREAD

**Issue by tiagoebatista** [guiaedutec/geos-backend#2]
Olá,

Primeiro quero agradece pela iniciativa de disponibilizar o código deste serviço que é sensacional!

Estou tendo dificuldades com a instalação. Segui os passos e consegui subir o 3 contêineres pelo docker. Entretanto estou enfrentando um problema de renderização da página. Quando acesso ela fica assim:

![image](https://user-images.githubusercontent.com/76497671/146848424-6aeaf652-2ba5-4513-b1d4-26d30c27cc77.png)

Estou rodando o *docker versão 20.10* no *ubuntu 21.10*

seguem as minhas configurações:

#### BANCO DE DADOS ####

```
version: "3.4"
services:
  mongo:
    image: mongo:4.2.12
    container_name: geos-database
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=cieb
      - MONGO_INITDB_DATABASE=guia_edutec
    ports:
      - "30998:27017"
    restart: unless-stopped
    networks:
      - geos-network
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  mongo-seed:
    build: ./mongo-seed
    networks:
      - geos-network
    depends_on:
      - mongo
    links:
      - mongo
networks:
  geos-network:

```

#### BACK-END ####

```

RAILS_ENV=development

# Standard database credentials
# We recommend changing the username and password in the database for security reasons!
MONGODB_HOST_1=host.docker.internal:30998
MONGODB_DATABASE=guia_edutec
MONGODB_USER=tiago
MONGODB_PASS=cieb

# Email settings
MAIL_SERVER=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=<user>
MAIL_PASSWORD=<senha>
MAIL_DOMAIN=tiagoebatista.com
MAIL_FROM=cieb@tiagoebatista.com
MAIL_SENDER=cieb@tiagoebatista.com

# Basic URLs
# Configure as needed
FRONTEND_URL=http://localhost:8001
BACKEND_URL=http://localhost:8000

# Insert a random hash with 128 characters, containing numbers and lowercase letters
# As the generator: https://www.browserling.com/tools/random-string
SECRET_KEY_BASE=pcrfdsfdsfsdfsdfsdfsdfcdfyoimtukucpcgtvxqtwnirgjjauujyjycccqltgibugxkgdxuyifhprxcimimoryqujmbcktpyeajsvlaowalvlkrasajxdstdavnniccnlzdwlbpvefdwwrzdp

```

#### FRONT-END 

```
API_URL="localhost:3000"

# Basic frontend settings
TITLE="Guia TB"
WEBSITE_URL="cieb.tiagoebatista.com"
PROJECT_NAME="CIEB TB"

# Google Analytics ID
TRACKING_ID=

# Default language
DEFAULT_LOCALE="pt-BR"

```

Imagino que seja um problema na conexão entre o front e o back-end, mas não tenho certeza e não consigo pensar em uma forma de resolver.

Desde já, agradeço pela sua atenção.
